import { StyleSheet } from "react-native";
export default  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    paddingHorizontal: 30,
    paddingVertical: 20,
  },
  logo: {
    width: 180,
    height: 180,
    alignSelf: "center",
    marginBottom: 30,
  },
  titleContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
    paddingHorizontal: 20,
  },
  titleText: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    color: "#170242ff",
    marginVertical: 5,
    lineHeight: 22,
  },

  inputcontainer: {
    alignItems: "center",
    paddingHorizontal: 10,
    marginTop: 20,
  },
  button: {
    backgroundColor: "#170242ff",
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginTop: 25,
    width: "100%",
    alignItems: "center",
    borderRadius: 10,
    shadowColor: "#170242ff",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  input: {
    height: 56,
    width: "100%",
    borderWidth: 2,
    borderColor: "#e0e0e0",
    borderRadius: 10,
    paddingHorizontal: 18,
    marginBottom: 16,
    backgroundColor: "#ffffff",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
    focusedBorderColor: "#170242ff",
  },
});