import { StyleSheet } from "react-native";

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#f8f9fa",
    padding: 16,
    paddingBottom: 0,  
  },
  header:{
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  headerLeft:{
    flex: 1,
  },
  headerCenter: {
    flex: 2,
    alignItems: "center",
  },
  headerRight: {
    flex: 1,
    alignItems: "flex-end",
    marginTop: 30,
    backgroundColor: "#b30618ff",
    alignItems: "center",
    justifyContent: "center",
    borderRadius:20,
marginLeft:10  },
  logoutText: {
    color: "#ffffffff",
    fontWeight: "bold",
    fontSize: 16,
    textAlign: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#170242ff",
    textAlign: "center",
    marginBottom: 15,
    marginTop: 20,  
    paddingTop: 20,
  },
  listContainer: {
    flex: 1,
    marginBottom: 0, 
    
  },
  buttonArea: {
    flex: 0.4,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  itemContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    marginTop:12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: "#170242ff",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  column: {
    flex: 1,
    marginRight: 10,
  },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  value: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
    flexWrap: "wrap",
  },
  addButton: {
    backgroundColor: "#170242ff",
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    width: "90%",
    alignItems: "center",
    shadowColor: "#170242ff",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
    margin:5,
  },
  addButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    letterSpacing: 1,
  },
  detail: {
    backgroundColor: "#170242ff",

    borderRadius: 8,
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    minWidth: 100,
    shadowColor: "#170242ff",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  detailText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  filterArea: {
    marginBottom:10,
    width:"8%",
    alignItems:"center",

  }
});
